require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClaimsController do

  # This should return the minimal set of attributes required to create a valid
  # Claim. As you add validations to Claim, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all claims as @claims" do
      claim = Claim.create! valid_attributes
      get :index
      assigns(:claims).should eq([claim])
    end
  end

  describe "GET show" do
    it "assigns the requested claim as @claim" do
      claim = Claim.create! valid_attributes
      get :show, :id => claim.id.to_s
      assigns(:claim).should eq(claim)
    end
  end

  describe "GET new" do
    it "assigns a new claim as @claim" do
      get :new
      assigns(:claim).should be_a_new(Claim)
    end
  end

  describe "GET edit" do
    it "assigns the requested claim as @claim" do
      claim = Claim.create! valid_attributes
      get :edit, :id => claim.id.to_s
      assigns(:claim).should eq(claim)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Claim" do
        expect {
          post :create, :claim => valid_attributes
        }.to change(Claim, :count).by(1)
      end

      it "assigns a newly created claim as @claim" do
        post :create, :claim => valid_attributes
        assigns(:claim).should be_a(Claim)
        assigns(:claim).should be_persisted
      end

      it "redirects to the created claim" do
        post :create, :claim => valid_attributes
        response.should redirect_to(Claim.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved claim as @claim" do
        # Trigger the behavior that occurs when invalid params are submitted
        Claim.any_instance.stub(:save).and_return(false)
        post :create, :claim => {}
        assigns(:claim).should be_a_new(Claim)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Claim.any_instance.stub(:save).and_return(false)
        post :create, :claim => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested claim" do
        claim = Claim.create! valid_attributes
        # Assuming there are no other claims in the database, this
        # specifies that the Claim created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Claim.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => claim.id, :claim => {'these' => 'params'}
      end

      it "assigns the requested claim as @claim" do
        claim = Claim.create! valid_attributes
        put :update, :id => claim.id, :claim => valid_attributes
        assigns(:claim).should eq(claim)
      end

      it "redirects to the claim" do
        claim = Claim.create! valid_attributes
        put :update, :id => claim.id, :claim => valid_attributes
        response.should redirect_to(claim)
      end
    end

    describe "with invalid params" do
      it "assigns the claim as @claim" do
        claim = Claim.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Claim.any_instance.stub(:save).and_return(false)
        put :update, :id => claim.id.to_s, :claim => {}
        assigns(:claim).should eq(claim)
      end

      it "re-renders the 'edit' template" do
        claim = Claim.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Claim.any_instance.stub(:save).and_return(false)
        put :update, :id => claim.id.to_s, :claim => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested claim" do
      claim = Claim.create! valid_attributes
      expect {
        delete :destroy, :id => claim.id.to_s
      }.to change(Claim, :count).by(-1)
    end

    it "redirects to the claims list" do
      claim = Claim.create! valid_attributes
      delete :destroy, :id => claim.id.to_s
      response.should redirect_to(claims_url)
    end
  end

end
